{
    # Import all your configuration modules here
    imports = [
        ./lsp.nix
        ./completion.nix
        ./keymaps.nix
        ./bufdelete.nix
        ./telescope.nix
        ./dressing.nix
        ./lualine.nix
        ./oil.nix
        ./whichkey.nix
        ./flash.nix
        ./gitsigns.nix
        ./todo-comments.nix
        ./indent-blankline.nix
        ./bufferline.nix
        ./catppuccin.nix
        ./autopairs.nix
        ./treesitter.nix
        ./toggleterm.nix
        ./options.nix
        ./noice.nix
        ./nvimtree.nix
        ./omen.nix
        ./comment.nix
        ./org.nix
        ./rainbow-delimiters.nix
        ./scope.nix
        ./sessions.nix
    ];
}
